/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.penggajian;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class laporanP extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(laporanP.class.getName());

    /**
     * Creates new form laporanP
     */
    public laporanP() {
        initComponents();
        
        
        // Di constructor - isi pilihan bulan
pilihBulan.removeAllItems(); // hapus Item 1
pilihBulan.addItem("2026-06");
pilihBulan.addItem("2026-07");
pilihBulan.addItem("2026-08");
pilihBulan.addItem("2026-09");
pilihBulan.addItem("2026-10");
pilihBulan.addItem("2026-11");

// ← TAMBAHKAN INI untuk pilihan tahun
    pilihTahun.removeAllItems();
    pilihTahun.addItem("2026");
    pilihTahun.addItem("2027");
        
        DefaultTableModel model = new DefaultTableModel();
model.addColumn("ID Pegawai");
model.addColumn("Nama");
model.addColumn("Periode");
model.addColumn("Tunjangan");
model.addColumn("Potongan");
model.addColumn("Total Kehadiran");
model.addColumn("Total Gaji");

Connection con = DBconnection.getKoneksi();

String sql = "SELECT pegawai.id_pegawai, pegawai.nama, " +
             "penggajian.periode, penggajian.tunjangan, " +
             "penggajian.potongan, penggajian.total_kehadiran, " +
             "penggajian.total_gaji " +
             "FROM penggajian " +
             "JOIN presensi ON penggajian.id_presensi = presensi.id_presensi " +
             "JOIN pegawai ON presensi.id_pegawai = pegawai.id_pegawai";
try {
    PreparedStatement ps = con.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getString("id_pegawai"),
            rs.getString("nama"),
            rs.getString("periode"),
            rs.getString("tunjangan"),
            rs.getString("potongan"),
            rs.getString("total_kehadiran"),
            rs.getString("total_gaji")
        });
    }
    tabelGaji.setModel(model);
} catch (Exception e) {
    
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_laporanDP = new javax.swing.JButton();
        btn_laporanP = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihBulan = new javax.swing.JComboBox<>();
        btn_Tampilkan = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        LabelTotalGaji = new javax.swing.JLabel();
        RpGaji = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        LabelTotalTunjangan = new javax.swing.JLabel();
        RpTunjangan = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        LabelTotalPotongan = new javax.swing.JLabel();
        RpPotongan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGaji = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pilihTahun = new javax.swing.JComboBox<>();
        btn_TampilkanTahun = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        LabelGajiTahun = new javax.swing.JLabel();
        RpGajiTahun = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        LabelPotonganTahun = new javax.swing.JLabel();
        RpPotonganTahun = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        LabelTunjanganTahun = new javax.swing.JLabel();
        RpTunjanganTahun = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelTahun = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(234, 749));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PEMILIK");

        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setMaximumSize(new java.awt.Dimension(125, 23));
        btn_dashboard.setMinimumSize(new java.awt.Dimension(125, 23));
        btn_dashboard.setPreferredSize(new java.awt.Dimension(125, 23));
        btn_dashboard.addActionListener(this::btn_dashboardActionPerformed);

        jLabel3.setText("LAPORAN");

        btn_laporanDP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_laporanDP.setText("Laporan Data Pegawai");
        btn_laporanDP.setMaximumSize(new java.awt.Dimension(125, 23));
        btn_laporanDP.setMinimumSize(new java.awt.Dimension(125, 23));
        btn_laporanDP.setPreferredSize(new java.awt.Dimension(125, 23));
        btn_laporanDP.addActionListener(this::btn_laporanDPActionPerformed);

        btn_laporanP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_laporanP.setText("Laporan Penggajian");
        btn_laporanP.setMaximumSize(new java.awt.Dimension(125, 23));
        btn_laporanP.setMinimumSize(new java.awt.Dimension(125, 23));
        btn_laporanP.setPreferredSize(new java.awt.Dimension(125, 23));
        btn_laporanP.addActionListener(this::btn_laporanPActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_laporanP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btn_laporanDP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_laporanDP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_laporanP, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("Laporan Penggajian");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(268, 41));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("SISTEM PENGGAJIAN");

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        jLabel6.setText("Direkture");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ahmad Santoso");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("AS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)))
                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_keluar)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("PILIH PERIODE");

        pilihBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pilihBulan.addActionListener(this::pilihBulanActionPerformed);

        btn_Tampilkan.setBackground(new java.awt.Color(0, 153, 51));
        btn_Tampilkan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Tampilkan.setText("Tampilkan");
        btn_Tampilkan.addActionListener(this::btn_TampilkanActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(pilihBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(btn_Tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Tampilkan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        LabelTotalGaji.setText("TOTAL GAJI POKOK");

        RpGaji.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RpGaji.setText("Rp ......");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelTotalGaji))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(RpGaji)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotalGaji)
                .addGap(28, 28, 28)
                .addComponent(RpGaji)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(160, 100));

        LabelTotalTunjangan.setText("TOTAL TUNJANGAN");

        RpTunjangan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RpTunjangan.setText("RP ........");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotalTunjangan)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RpTunjangan)
                .addGap(55, 55, 55))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotalTunjangan)
                .addGap(27, 27, 27)
                .addComponent(RpTunjangan)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(160, 100));

        LabelTotalPotongan.setText("TOTAL POTONGAN");

        RpPotongan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RpPotongan.setText("Rp ...........");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelTotalPotongan))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(RpPotongan)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotalPotongan)
                .addGap(18, 18, 18)
                .addComponent(RpPotongan)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabelGaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelGaji);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jTabbedPane1.addTab("Laporan Bulanan", jPanel4);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("PILIH TAHUN");

        pilihTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pilihTahun.addActionListener(this::pilihTahunActionPerformed);

        btn_TampilkanTahun.setBackground(new java.awt.Color(0, 153, 51));
        btn_TampilkanTahun.setText("Tampilkan");
        btn_TampilkanTahun.addActionListener(this::btn_TampilkanTahunActionPerformed);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(pilihTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_TampilkanTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pilihTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TampilkanTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(160, 100));

        LabelGajiTahun.setText("TOTAL GAJI");

        RpGajiTahun.setText("Rp .......");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelGajiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RpGajiTahun))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelGajiTahun)
                .addGap(27, 27, 27)
                .addComponent(RpGajiTahun)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(160, 100));

        LabelPotonganTahun.setText("TOTAL POTONGAN");

        RpPotonganTahun.setText("Rp ............");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(RpPotonganTahun))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelPotonganTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPotonganTahun)
                .addGap(30, 30, 30)
                .addComponent(RpPotonganTahun)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(160, 100));

        LabelTunjanganTahun.setText("TOTAL TUNJANGAN");

        RpTunjanganTahun.setText("Rp ............");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(RpTunjanganTahun))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelTunjanganTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTunjanganTahun)
                .addGap(18, 18, 18)
                .addComponent(RpTunjanganTahun)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        TabelTahun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TabelTahun);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laporan Tahunan", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_laporanPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_laporanPActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        // TODO add your handling code here:
        dashboard obj = new dashboard();
        obj.setVisible(true);
        dispose();
        
     
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_laporanDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanDPActionPerformed
        // TODO add your handling code here:
        laporanDP obj = new laporanDP();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_laporanDPActionPerformed

    private void btn_TampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TampilkanActionPerformed
        // TODO add your handling code here:
        
       
    String periode = pilihBulan.getSelectedItem().toString();
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pegawai");
    model.addColumn("Nama");
    model.addColumn("Periode");
    model.addColumn("Tunjangan");
    model.addColumn("Potongan");
    model.addColumn("Total Kehadiran");
    model.addColumn("Total Gaji");
    
    Connection con = DBconnection.getKoneksi();
    
    String sql = "SELECT pegawai.id_pegawai, pegawai.nama, " +
                 "penggajian.periode, penggajian.tunjangan, " +
                 "penggajian.potongan, penggajian.total_kehadiran, " +
                 "penggajian.total_gaji " +
                 "FROM penggajian " +
                 "JOIN presensi ON penggajian.id_presensi = presensi.id_presensi " +
                 "JOIN pegawai ON presensi.id_pegawai = pegawai.id_pegawai " +
                 "WHERE penggajian.periode = ?";
    try {
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, periode);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pegawai"),
                rs.getString("nama"),
                rs.getString("periode"),
                rs.getString("tunjangan"),
                rs.getString("potongan"),
                rs.getString("total_kehadiran"),
                rs.getString("total_gaji")
            });
        }
        tabelGaji.setModel(model);
        
    } catch (Exception e) {
        
    
        }
    
    String sqlTotal = "SELECT SUM(tunjangan) as total_tunjangan, " +
                  "SUM(potongan) as total_potongan, " +
                  "SUM(total_gaji) as total_gaji " +
                  "FROM penggajian " +
                  "WHERE periode = ?";
try {
    PreparedStatement ps2 = con.prepareStatement(sqlTotal);
    ps2.setString(1, periode);
    ResultSet rs2 = ps2.executeQuery();
    if (rs2.next()) {
        RpGaji.setText("Rp " + rs2.getString("total_gaji"));
        RpTunjangan.setText("Rp " + rs2.getString("total_tunjangan"));
        RpPotongan.setText("Rp " + rs2.getString("total_potongan"));
    }
} catch (Exception e) {
    
}
    }//GEN-LAST:event_btn_TampilkanActionPerformed

    private void pilihBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBulanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pilihBulanActionPerformed

    private void pilihTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihTahunActionPerformed

    private void btn_TampilkanTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TampilkanTahunActionPerformed
        // TODO add your handling code here:
        tampilkanLaporanTahunan();
    }//GEN-LAST:event_btn_TampilkanTahunActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        Login obj = new Login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed
     
      private void tampilkanLaporanTahunan() {
    String tahun = pilihTahun.getSelectedItem().toString();
    
    String[] namaBulan = {"", "Juni", "Juli", "Agustus", "September",
                          "Oktober", "November", "Desember", "Januari",
                          "Februari", "Maret", "April", "Mei"};
    
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Bulan");
    model.addColumn("Total Gaji");
    model.addColumn("Total Tunjangan");
    model.addColumn("Total Potongan");
    
    java.util.Map<Integer, long[]> dataMap = new java.util.HashMap<>();
    
    Connection con = DBconnection.getKoneksi();
    String sql = "SELECT periode, " +
                 "SUM(total_gaji) as total_gaji, " +
                 "SUM(tunjangan) as total_tunjangan, " +
                 "SUM(potongan) as total_potongan " +
                 "FROM penggajian " +
                 "WHERE periode LIKE ? " +
                 "GROUP BY periode " +
                 "ORDER BY periode ASC";
    
    try {
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, tahun + "%");
        ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            String periode = rs.getString("periode");
            int bulanAngka = Integer.parseInt(periode.split("-")[1]);
            dataMap.put(bulanAngka, new long[]{
                rs.getLong("total_gaji"),
                rs.getLong("total_tunjangan"),
                rs.getLong("total_potongan")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    long grandGaji = 0, grandTunjangan = 0, grandPotongan = 0;
    
    for (int b = 1; b <= 12; b++) {
        if (dataMap.containsKey(b)) {
            long[] d = dataMap.get(b);
            grandGaji += d[0];
            grandTunjangan += d[1];
            grandPotongan += d[2];
            model.addRow(new Object[]{
                namaBulan[b],
                "Rp " + d[0],
                "Rp " + d[1],
                "Rp " + d[2]
            });
        } else {
            model.addRow(new Object[]{
                namaBulan[b], "...", "...", "..."
            });
        }
    }
    
    TabelTahun.setModel(model);
    RpGajiTahun.setText("Rp " + grandGaji);
    RpPotonganTahun.setText("Rp " + grandPotongan);
    RpTunjanganTahun.setText("Rp " + grandTunjangan);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new laporanP().setVisible(true));
    }

    
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelGajiTahun;
    private javax.swing.JLabel LabelPotonganTahun;
    private javax.swing.JLabel LabelTotalGaji;
    private javax.swing.JLabel LabelTotalPotongan;
    private javax.swing.JLabel LabelTotalTunjangan;
    private javax.swing.JLabel LabelTunjanganTahun;
    private javax.swing.JLabel RpGaji;
    private javax.swing.JLabel RpGajiTahun;
    private javax.swing.JLabel RpPotongan;
    private javax.swing.JLabel RpPotonganTahun;
    private javax.swing.JLabel RpTunjangan;
    private javax.swing.JLabel RpTunjanganTahun;
    private javax.swing.JTable TabelTahun;
    private javax.swing.JButton btn_Tampilkan;
    private javax.swing.JButton btn_TampilkanTahun;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_laporanDP;
    private javax.swing.JButton btn_laporanP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> pilihBulan;
    private javax.swing.JComboBox<String> pilihTahun;
    private javax.swing.JTable tabelGaji;
    // End of variables declaration//GEN-END:variables
}
