/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistempenggajian;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Presensi extends javax.swing.JFrame {

    private int idPegawai;
    private String nama, jabatan, email, telepon, alamat, inisial;

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(Presensi.class.getName());

    // CONSTRUCTOR
    public Presensi(int idPegawai, String nama, String jabatan, String inisial) {
        initComponents();

        this.idPegawai = idPegawai;
        this.nama = nama;
        this.jabatan = jabatan;
        this.inisial = inisial;

        txtTanggal.setText(java.time.LocalDate.now().toString());
        txtJam.setText(java.time.LocalTime.now().withNano(0).toString());
        txtTanggal.setEditable(false);
        txtJam.setEditable(false);
        txtNama.setEditable(false);
        txtNik.setEditable(false);

        loadDataPegawai(idPegawai);

        jLabel16.setText(inisial);
        jLabel17.setText(nama);
        jLabel18.setText(jabatan);

        btnKeluar.addActionListener(evt -> {
            int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (pilih == JOptionPane.YES_OPTION) {
                new Login().setVisible(true);
                dispose();
            }
        });

        loadTable(idPegawai);

        lblBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TampilanUtamaPegawai beranda = new TampilanUtamaPegawai(
                        nama, jabatan, "", "", "", inisial, idPegawai
                );
                beranda.setVisible(true);
                dispose();
            }
        });

        lblSlipGaji.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                SlipGaji sg = new SlipGaji(
                        idPegawai,
                        nama,
                        jabatan,
                        inisial
                );

                sg.setVisible(true);
                dispose();
            }
        });

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblMenuPegawai6 = new javax.swing.JLabel();
        lblBeranda = new javax.swing.JLabel();
        lblPresensi = new javax.swing.JLabel();
        lblSlipGaji = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblJudul5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNik = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbJenisPresensi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtJam = new javax.swing.JTextField();
        btnKirimPresensi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        scrollRiwayatPresensi = new javax.swing.JScrollPane();
        tblRiwayatPresensi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblMenuPegawai6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMenuPegawai6.setForeground(new java.awt.Color(0, 0, 0));
        lblMenuPegawai6.setText("Menu Pegawai");

        lblBeranda.setForeground(new java.awt.Color(0, 0, 0));
        lblBeranda.setText("🏠 Beranda");

        lblPresensi.setForeground(new java.awt.Color(0, 0, 0));
        lblPresensi.setText("📅 Presensi");
        lblPresensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPresensiMouseClicked(evt);
            }
        });

        lblSlipGaji.setForeground(new java.awt.Color(0, 0, 0));
        lblSlipGaji.setText("📄 Slip Gaji ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenuPegawai6)
                    .addComponent(lblBeranda)
                    .addComponent(lblPresensi)
                    .addComponent(lblSlipGaji))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblMenuPegawai6)
                .addGap(18, 18, 18)
                .addComponent(lblBeranda)
                .addGap(18, 18, 18)
                .addComponent(lblPresensi)
                .addGap(18, 18, 18)
                .addComponent(lblSlipGaji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        lblJudul5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul5.setForeground(new java.awt.Color(0, 0, 0));
        lblJudul5.setText("Sistem Penggajian");
        lblJudul5.setMaximumSize(new java.awt.Dimension(100, 100));
        lblJudul5.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 0));
        jLabel16.setText("AP");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Andi Pratama");

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Staff Admin");

        btnKeluar.setBackground(new java.awt.Color(204, 204, 204));
        btnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluar.setText("Keluar");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addGap(21, 21, 21))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnKeluar)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudul5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Input Presensi Hari Ini ");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama Lengkap ");
        jLabel4.setToolTipText("");

        txtNama.setEditable(false);
        txtNama.setBackground(new java.awt.Color(204, 204, 204));
        txtNama.setForeground(new java.awt.Color(0, 0, 0));
        txtNama.setText("Andi Pratama");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("NIK / ID Pegawai ");

        txtNik.setEditable(false);
        txtNik.setBackground(new java.awt.Color(204, 204, 204));
        txtNik.setForeground(new java.awt.Color(0, 0, 0));
        txtNik.setText("ALS-010");

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Jenis Presensi ");

        cmbJenisPresensi.setBackground(new java.awt.Color(204, 204, 204));
        cmbJenisPresensi.setForeground(new java.awt.Color(0, 0, 0));
        cmbJenisPresensi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masuk Kerja", "Pulang Kerja", "izin" }));

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Tanggal ");

        txtTanggal.setEditable(false);
        txtTanggal.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Jam ");

        txtJam.setEditable(false);
        txtJam.setBackground(new java.awt.Color(204, 204, 204));

        btnKirimPresensi.setBackground(new java.awt.Color(0, 102, 0));
        btnKirimPresensi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKirimPresensi.setForeground(new java.awt.Color(255, 255, 255));
        btnKirimPresensi.setText("Kirim Presensi");
        btnKirimPresensi.addActionListener(this::btnKirimPresensiActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 253, Short.MAX_VALUE))
                    .addComponent(txtNik)
                    .addComponent(cmbJenisPresensi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTanggal)
                    .addComponent(txtJam)
                    .addComponent(btnKirimPresensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbJenisPresensi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKirimPresensi)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Presensi ");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Catat kehadiran kamu hari ini\n\n\n");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Riwayat Presensi — Juni 2026");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        tblRiwayatPresensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Masuk", "Pulang", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollRiwayatPresensi.setViewportView(tblRiwayatPresensi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollRiwayatPresensi, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollRiwayatPresensi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPresensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPresensiMouseClicked
        // TODO add your handling code here:
        Presensi p = new Presensi(
                idPegawai,
                nama,
                jabatan,
                inisial
        );
        p.setVisible(true);
        dispose();

    }//GEN-LAST:event_lblPresensiMouseClicked

    private void btnKirimPresensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimPresensiActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DBConnection.getKoneksi();
            String pilihan = cmbJenisPresensi.getSelectedItem().toString();
            String tanggal = txtTanggal.getText();
            String jam = txtJam.getText();

            if (pilihan.equals("Masuk Kerja")) {

                // Cek apakah sudah presensi hari ini
                String cek = "SELECT * FROM presensi WHERE id_pegawai=? AND tgl_presensi=?";
                PreparedStatement psCek = con.prepareStatement(cek);
                psCek.setInt(1, idPegawai);
                psCek.setString(2, tanggal);

                ResultSet rsCek = psCek.executeQuery();

                if (rsCek.next()) {
                    JOptionPane.showMessageDialog(this,
                            "Anda sudah melakukan presensi hari ini!");
                    return;
                }

                java.time.LocalTime jamMasuk = java.time.LocalTime.parse(jam);
                java.time.LocalTime batas = java.time.LocalTime.of(8, 0);
                String status = jamMasuk.isAfter(batas) ? "terlambat" : "hadir";

                String sql = "INSERT INTO presensi (id_pegawai, tgl_presensi, jam_masuk, status_presensi) VALUES (?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, idPegawai);
                ps.setString(2, tanggal);
                ps.setString(3, jam);
                ps.setString(4, status);
                ps.executeUpdate();

            } else if (pilihan.equals("Pulang Kerja")) {
                String cek = "SELECT * FROM presensi WHERE id_pegawai=? AND tgl_presensi=?";
                PreparedStatement psCek = con.prepareStatement(cek);
                psCek.setInt(1, idPegawai);
                psCek.setString(2, tanggal);

                ResultSet rsCek = psCek.executeQuery();

                if (rsCek.next()) {
                    JOptionPane.showMessageDialog(this,
                            "Presensi hari ini sudah ada!");
                    return;
                }

                String sql = "UPDATE presensi SET jam_pulang = ? WHERE id_pegawai = ? AND tgl_presensi = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, jam);
                ps.setInt(2, idPegawai);
                ps.setString(3, tanggal);
                int rows = ps.executeUpdate();

                if (rows == 0) {
                    JOptionPane.showMessageDialog(this, "Belum ada presensi Masuk Kerja hari ini!");
                    return;
                }

            } else { // izin
                String sql = "INSERT INTO presensi (id_pegawai, tgl_presensi, status_presensi) VALUES (?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, idPegawai);
                ps.setString(2, tanggal);
                ps.setString(3, "izin");
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Presensi berhasil disimpan!");
            loadTable(idPegawai);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnKirimPresensiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()
                -> new Presensi(0, "", "", "").setVisible(true)
        );
    }

    private void loadTable(int idPegawai) {
        try {

            Connection con = DBConnection.getKoneksi();

            String sql = "SELECT tgl_presensi, jam_masuk, jam_pulang, status_presensi "
                    + "FROM presensi WHERE id_pegawai = ? ORDER BY tgl_presensi DESC";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idPegawai);

            ResultSet rs = ps.executeQuery();

            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblRiwayatPresensi.getModel();

            model.setRowCount(0);

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getString("tgl_presensi"),
                    rs.getString("jam_masuk"),
                    rs.getString("jam_pulang"),
                    rs.getString("status_presensi")

                });

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }

    }

    private void loadDataPegawai(int idPegawai) {
        String sql = "SELECT nama, nik FROM pegawai WHERE id_pegawai = ?";
        java.sql.Connection conn = DBConnection.getKoneksi();
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, idPegawai);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtNama.setText(rs.getString("nama"));
                txtNik.setText(rs.getString("nik"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKirimPresensi;
    private javax.swing.JComboBox<String> cmbJenisPresensi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBeranda;
    private javax.swing.JLabel lblJudul5;
    private javax.swing.JLabel lblMenuPegawai6;
    private javax.swing.JLabel lblPresensi;
    private javax.swing.JLabel lblSlipGaji;
    private javax.swing.JScrollPane scrollRiwayatPresensi;
    private javax.swing.JTable tblRiwayatPresensi;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
