/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistempenggajian;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ASUS
 */
public class TampilanUtamaPegawai extends javax.swing.JFrame {

    private int idPegawai;
    private String nama, jabatan, email, telepon, alamat, inisial;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TampilanUtamaPegawai.class.getName());

    /**
     * Creates new form TampilanUtamaPegawai
     */
    public TampilanUtamaPegawai() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    public TampilanUtamaPegawai(String nama,
            String jabatan,
            String email,
            String telepon,
            String alamat,
            String inisial,
            int idPegawai) {

        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.idPegawai = idPegawai;

        lblNama.setText(nama);
        lblJabatan.setText(jabatan + " · " + getNIK(idPegawai));
        lblEmail.setText(email);
        lblTelepon.setText(telepon);
        lbl_Jabatan.setText(jabatan);
        lblAlamat.setText(alamat);
        lblInisial.setText(inisial);
        lblHeaderInisial.setText(inisial);
        lblHeaderNama.setText(nama);
        lblHeaderJabatan.setText(jabatan);
        lblWelcome.setText("Selamat datang, " + nama);

        loadDataKehadiran(idPegawai);
        loadDataGaji(idPegawai);

        btnLihatSlipGaji.addActionListener(evt -> {
            SlipGaji slip = new SlipGaji(
                    idPegawai,
                    lblNama.getText(),
                    lbl_Jabatan.getText(),
                    lblInisial.getText()
            );
            slip.setVisible(true);
            dispose();
        });
    }

    private String getNIK(int idPegawai) {
        String nik = "";
        String sql = "SELECT nik FROM pegawai WHERE id_pegawai = ?";
        java.sql.Connection conn = DBConnection.getKoneksi();
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, idPegawai);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                nik = rs.getString("nik");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return nik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblHeaderInisial = new javax.swing.JLabel();
        lblHeaderNama = new javax.swing.JLabel();
        lblHeaderJabatan = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        panelSidebar = new javax.swing.JPanel();
        lblMenuPegawai = new javax.swing.JLabel();
        lblBeranda = new javax.swing.JLabel();
        lblPresensi = new javax.swing.JLabel();
        lblSlipGaji = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelProfil = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        lblInisial = new javax.swing.JLabel();
        lblJabatan = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelepon = new javax.swing.JLabel();
        lbl_Jabatan = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblJudulHalaman = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        panelGaji = new javax.swing.JPanel();
        lblGajiBulanIni = new javax.swing.JLabel();
        lblTotalGaji = new javax.swing.JLabel();
        lblPeriode = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnLihatSlipGaji = new javax.swing.JButton();
        lblGajiPokok = new javax.swing.JLabel();
        lblTunjangan = new javax.swing.JLabel();
        lblPotongan = new javax.swing.JLabel();
        panelKehadiran = new javax.swing.JPanel();
        lblRingkasanHadir = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        panelHadir = new javax.swing.JPanel();
        lblHadir = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        panelIzin = new javax.swing.JPanel();
        lblIzin = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        panelSakit = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        lblSakit = new javax.swing.JLabel();
        panelAlpha = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lblAlpha = new javax.swing.JLabel();
        lblJudulKehadiran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUtama.setBackground(new java.awt.Color(204, 204, 204));
        panelUtama.setPreferredSize(new java.awt.Dimension(1143, 726));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(0, 0, 0));
        lblJudul.setText("Sistem Penggajian");
        lblJudul.setMaximumSize(new java.awt.Dimension(100, 100));
        lblJudul.setMinimumSize(new java.awt.Dimension(100, 100));

        lblHeaderInisial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeaderInisial.setForeground(new java.awt.Color(51, 102, 0));
        lblHeaderInisial.setText("AP");

        lblHeaderNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeaderNama.setForeground(new java.awt.Color(0, 0, 0));
        lblHeaderNama.setText("Andi Pratama");

        lblHeaderJabatan.setForeground(new java.awt.Color(51, 51, 51));
        lblHeaderJabatan.setText("Staff Admin");

        btnKeluar.setBackground(new java.awt.Color(204, 204, 204));
        btnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeaderInisial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeaderNama)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblHeaderJabatan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addGap(21, 21, 21))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnKeluar)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                                .addComponent(lblHeaderJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeaderInisial)
                            .addComponent(lblHeaderNama))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        panelSidebar.setBackground(new java.awt.Color(255, 255, 255));

        lblMenuPegawai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMenuPegawai.setForeground(new java.awt.Color(0, 0, 0));
        lblMenuPegawai.setText("Menu Pegawai");

        lblBeranda.setForeground(new java.awt.Color(0, 0, 0));
        lblBeranda.setText("🏠 Beranda");
        lblBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBerandaMouseClicked(evt);
            }
        });

        lblPresensi.setForeground(new java.awt.Color(0, 0, 0));
        lblPresensi.setText("📅 Presensi");
        lblPresensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPresensiMouseClicked(evt);
            }
        });

        lblSlipGaji.setForeground(new java.awt.Color(0, 0, 0));
        lblSlipGaji.setText("📄 Slip Gaji ");

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenuPegawai)
                    .addComponent(lblBeranda)
                    .addComponent(lblPresensi)
                    .addComponent(lblSlipGaji))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblMenuPegawai)
                .addGap(18, 18, 18)
                .addComponent(lblBeranda)
                .addGap(18, 18, 18)
                .addComponent(lblPresensi)
                .addGap(18, 18, 18)
                .addComponent(lblSlipGaji)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        panelContent.setBackground(new java.awt.Color(204, 204, 204));
        panelContent.setPreferredSize(new java.awt.Dimension(1143, 726));

        panelProfil.setBackground(new java.awt.Color(255, 255, 255));
        panelProfil.setForeground(new java.awt.Color(0, 0, 0));

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        lblNama.setText("Andi Pratama");

        lblInisial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInisial.setForeground(new java.awt.Color(51, 102, 0));
        lblInisial.setText("AP");

        lblJabatan.setBackground(new java.awt.Color(102, 102, 102));
        lblJabatan.setForeground(new java.awt.Color(51, 51, 51));
        lblJabatan.setText("Staff Admin · ALS-010");

        lblStatus.setForeground(new java.awt.Color(51, 102, 0));
        lblStatus.setText("Aktif");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Email");

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("No. Telepon ");

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Jabatan");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Alamat");

        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText(" andi@alifasa.co.id");

        lblTelepon.setForeground(new java.awt.Color(0, 0, 0));
        lblTelepon.setText(" 0812-9999-0000");

        lbl_Jabatan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Jabatan.setText(" Staff Admin");

        lblAlamat.setForeground(new java.awt.Color(0, 0, 0));
        lblAlamat.setText("Jl. Veteran No. 5, Surakarta");

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblInisial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(129, 129, 129)
                        .addComponent(lblAlamat))
                    .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(125, 125, 125)
                            .addComponent(lbl_Jabatan))
                        .addGroup(panelProfilLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(132, 132, 132)
                            .addComponent(lblEmail))
                        .addComponent(lblStatus)
                        .addComponent(lblJabatan)
                        .addComponent(lblNama)
                        .addGroup(panelProfilLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(97, 97, 97)
                            .addComponent(lblTelepon))
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelProfilLayout.setVerticalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJabatan))
                    .addComponent(lblInisial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addGap(56, 56, 56)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblEmail))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblTelepon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbl_Jabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblAlamat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblJudulHalaman.setBackground(new java.awt.Color(0, 0, 0));
        lblJudulHalaman.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudulHalaman.setForeground(new java.awt.Color(0, 0, 0));
        lblJudulHalaman.setText("Beranda Pegawai");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 0));
        lblWelcome.setText("Selamat datang, Andi Pratama ");

        panelGaji.setBackground(new java.awt.Color(255, 255, 255));

        lblGajiBulanIni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGajiBulanIni.setForeground(new java.awt.Color(0, 0, 0));
        lblGajiBulanIni.setText("Gaji Bulan Ini");

        lblTotalGaji.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalGaji.setForeground(new java.awt.Color(51, 102, 0));
        lblTotalGaji.setText("Rp 4.350.000 ");

        lblPeriode.setForeground(new java.awt.Color(51, 51, 51));
        lblPeriode.setText("Periode: Juni 2026 ");

        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Gaji Pokok ");

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Total Tunjangan");

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));

        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Total Potongan");

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));

        btnLihatSlipGaji.setBackground(new java.awt.Color(51, 102, 0));
        btnLihatSlipGaji.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLihatSlipGaji.setText("Lihat Slip Gaji");
        btnLihatSlipGaji.addActionListener(this::btnLihatSlipGajiActionPerformed);

        lblGajiPokok.setForeground(new java.awt.Color(0, 0, 0));
        lblGajiPokok.setText(" Rp 3.500.000");

        lblTunjangan.setForeground(new java.awt.Color(51, 102, 0));
        lblTunjangan.setText("+ Rp 1.000.000");

        lblPotongan.setForeground(new java.awt.Color(153, 0, 0));
        lblPotongan.setText(" - Rp 150.000");

        javax.swing.GroupLayout panelGajiLayout = new javax.swing.GroupLayout(panelGaji);
        panelGaji.setLayout(panelGajiLayout);
        panelGajiLayout.setHorizontalGroup(
            panelGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGajiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addGroup(panelGajiLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(144, 144, 144)
                        .addComponent(lblPotongan))
                    .addComponent(jSeparator5)
                    .addGroup(panelGajiLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(141, 141, 141)
                        .addComponent(lblTunjangan))
                    .addComponent(jSeparator4)
                    .addGroup(panelGajiLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(162, 162, 162)
                        .addComponent(lblGajiPokok))
                    .addComponent(lblPeriode)
                    .addComponent(lblTotalGaji)
                    .addComponent(lblGajiBulanIni)
                    .addComponent(btnLihatSlipGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelGajiLayout.setVerticalGroup(
            panelGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGajiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblGajiBulanIni)
                .addGap(38, 38, 38)
                .addComponent(lblTotalGaji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeriode)
                .addGap(28, 28, 28)
                .addGroup(panelGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblGajiPokok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblTunjangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblPotongan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLihatSlipGaji)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelKehadiran.setBackground(new java.awt.Color(255, 255, 255));
        panelKehadiran.setForeground(new java.awt.Color(255, 255, 255));

        lblRingkasanHadir.setBackground(new java.awt.Color(0, 0, 0));
        lblRingkasanHadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRingkasanHadir.setForeground(new java.awt.Color(51, 102, 0));
        lblRingkasanHadir.setText("22/22 hari hadir ");

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));

        panelHadir.setBackground(new java.awt.Color(204, 204, 204));

        lblHadir.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblHadir.setForeground(new java.awt.Color(51, 102, 0));
        lblHadir.setText("22");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Hadir");

        javax.swing.GroupLayout panelHadirLayout = new javax.swing.GroupLayout(panelHadir);
        panelHadir.setLayout(panelHadirLayout);
        panelHadirLayout.setHorizontalGroup(
            panelHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHadirLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHadir))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelHadirLayout.setVerticalGroup(
            panelHadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(11, 11, 11))
        );

        panelIzin.setBackground(new java.awt.Color(204, 204, 204));

        lblIzin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIzin.setForeground(new java.awt.Color(0, 0, 0));
        lblIzin.setText("0");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Izin");

        javax.swing.GroupLayout panelIzinLayout = new javax.swing.GroupLayout(panelIzin);
        panelIzin.setLayout(panelIzinLayout);
        panelIzinLayout.setHorizontalGroup(
            panelIzinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzinLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(panelIzinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(lblIzin))
                .addGap(81, 81, 81))
        );
        panelIzinLayout.setVerticalGroup(
            panelIzinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIzin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSakit.setBackground(new java.awt.Color(204, 204, 204));

        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Sakit");

        lblSakit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSakit.setForeground(new java.awt.Color(0, 0, 0));
        lblSakit.setText("0");

        javax.swing.GroupLayout panelSakitLayout = new javax.swing.GroupLayout(panelSakit);
        panelSakit.setLayout(panelSakitLayout);
        panelSakitLayout.setHorizontalGroup(
            panelSakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSakitLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelSakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSakit)
                    .addComponent(jLabel37))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        panelSakitLayout.setVerticalGroup(
            panelSakitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSakitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSakit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addGap(14, 14, 14))
        );

        panelAlpha.setBackground(new java.awt.Color(204, 204, 204));

        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Alpha");

        lblAlpha.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAlpha.setForeground(new java.awt.Color(153, 0, 0));
        lblAlpha.setText("0");

        javax.swing.GroupLayout panelAlphaLayout = new javax.swing.GroupLayout(panelAlpha);
        panelAlpha.setLayout(panelAlphaLayout);
        panelAlphaLayout.setHorizontalGroup(
            panelAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlphaLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panelAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(lblAlpha))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        panelAlphaLayout.setVerticalGroup(
            panelAlphaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlphaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(14, 14, 14))
        );

        lblJudulKehadiran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudulKehadiran.setForeground(new java.awt.Color(0, 0, 0));
        lblJudulKehadiran.setText("Kehadiran Bulan Ini ");

        javax.swing.GroupLayout panelKehadiranLayout = new javax.swing.GroupLayout(panelKehadiran);
        panelKehadiran.setLayout(panelKehadiranLayout);
        panelKehadiranLayout.setHorizontalGroup(
            panelKehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator7)
            .addGroup(panelKehadiranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelKehadiranLayout.createSequentialGroup()
                        .addComponent(panelHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelIzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(panelKehadiranLayout.createSequentialGroup()
                        .addComponent(lblJudulKehadiran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRingkasanHadir)
                        .addGap(24, 24, 24))))
        );
        panelKehadiranLayout.setVerticalGroup(
            panelKehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKehadiranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRingkasanHadir)
                    .addComponent(lblJudulKehadiran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSakit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelIzin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudulHalaman)
                    .addComponent(lblWelcome)
                    .addGroup(panelContentLayout.createSequentialGroup()
                        .addComponent(panelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulHalaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(26, 26, 26)
                .addGroup(panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(panelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPresensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPresensiMouseClicked
        // TODO add your handling code here:
        Presensi p = new Presensi(
                idPegawai,
                lblNama.getText(),
                lbl_Jabatan.getText(),
                lblInisial.getText()
        );
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblPresensiMouseClicked

    private void lblBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBerandaMouseClicked
        // TODO add your handling code here:
        TampilanUtamaPegawai home = new TampilanUtamaPegawai(
                lblNama.getText(),
                lbl_Jabatan.getText(),
                lblEmail.getText(),
                lblTelepon.getText(),
                lblAlamat.getText(),
                lblInisial.getText(),
                idPegawai
        );
        home.setVisible(true);
        dispose();

    }//GEN-LAST:event_lblBerandaMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (pilih == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }
    }

    private void loadDataKehadiran(int idPegawai) {
        java.time.LocalDate now = java.time.LocalDate.now();
        int bulan = now.getMonthValue();
        int tahun = now.getYear();

        java.time.LocalDate awalBulan = java.time.LocalDate.of(tahun, bulan, 1);
        int totalHariKerja = 0;
        for (java.time.LocalDate d = awalBulan; !d.isAfter(now); d = d.plusDays(1)) {
            java.time.DayOfWeek hari = d.getDayOfWeek();
            if (hari != java.time.DayOfWeek.SATURDAY && hari != java.time.DayOfWeek.SUNDAY) {
                totalHariKerja++;
            }
        }

        String sql = "SELECT "
                + "SUM(CASE WHEN status_presensi IN ('hadir','terlambat') THEN 1 ELSE 0 END) AS hadir, "
                + "SUM(CASE WHEN status_presensi = 'izin' THEN 1 ELSE 0 END) AS izin, "
                + "COUNT(*) AS total_tercatat "
                + "FROM presensi "
                + "WHERE id_pegawai = ? "
                + "AND MONTH(tgl_presensi) = ? AND YEAR(tgl_presensi) = ?";

        java.sql.Connection conn = DBConnection.getKoneksi();
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idPegawai);
            ps.setInt(2, bulan);
            ps.setInt(3, tahun);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                int hadir = rs.getInt("hadir");
                int izin = rs.getInt("izin");
                int totalTercatat = rs.getInt("total_tercatat");
                int alpha = Math.max(0, totalHariKerja - totalTercatat);

                lblHadir.setText(String.valueOf(hadir));
                lblIzin.setText(String.valueOf(izin));
                lblSakit.setText("0");
                lblAlpha.setText(String.valueOf(alpha));
                lblRingkasanHadir.setText(hadir + "/" + totalHariKerja + " hari hadir");
            }

        } catch (Exception e) {
            e.printStackTrace();
            lblHadir.setText("0");
            lblIzin.setText("0");
            lblAlpha.setText("0");
            lblRingkasanHadir.setText("0/" + totalHariKerja + " hari hadir");
        }
    }

    private void loadDataGaji(int idPegawai) {
        java.time.LocalDate now = java.time.LocalDate.now();
        String periodeBulanIni = now.getYear() + "-" + String.format("%02d", now.getMonthValue());

        String sql = "SELECT pg.tunjangan, pg.potongan, pg.total_gaji, pg.periode, "
                + "j.gaji_pokok "
                + "FROM penggajian pg "
                + "JOIN pegawai p ON pg.id_penggajian = p.id_pegawai "
                + "JOIN jabatan j ON p.id_jabatan = j.id_jabatan "
                + "WHERE p.id_pegawai = ? AND pg.periode = ? "
                + "LIMIT 1";

        java.sql.Connection conn = DBConnection.getKoneksi();
        try (java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idPegawai);
            ps.setString(2, periodeBulanIni);
            java.sql.ResultSet rs = ps.executeQuery();

            java.text.NumberFormat fmt = new java.text.DecimalFormat("#,###");

            if (rs.next()) {
                double gajiPokok = rs.getDouble("gaji_pokok");
                double tunjangan = rs.getDouble("tunjangan");
                double potongan = rs.getDouble("potongan");
                double totalGaji = rs.getDouble("total_gaji");

                String periode = rs.getString("periode");
                String[] pecah = periode.split("-");
                String[] namaBulan = {"", "Januari", "Februari", "Maret", "April", "Mei", "Juni",
                    "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
                int bln = Integer.parseInt(pecah[1]);
                lblPeriode.setText("Periode: " + namaBulan[bln] + " " + pecah[0]);

                lblGajiPokok.setText("Rp " + fmt.format(gajiPokok));
                lblTunjangan.setText("+ Rp " + fmt.format(tunjangan));
                lblPotongan.setText("- Rp " + fmt.format(potongan));
                lblTotalGaji.setText("Rp " + fmt.format(totalGaji));

            } else {
                String sqlGajiPokok = "SELECT j.gaji_pokok FROM pegawai p "
                        + "JOIN jabatan j ON p.id_jabatan = j.id_jabatan "
                        + "WHERE p.id_pegawai = ?";
                try (java.sql.PreparedStatement ps2 = conn.prepareStatement(sqlGajiPokok)) {
                    ps2.setInt(1, idPegawai);
                    java.sql.ResultSet rs2 = ps2.executeQuery();
                    if (rs2.next()) {
                        double gajiPokok = rs2.getDouble("gaji_pokok");
                        lblGajiPokok.setText("Rp " + fmt.format(gajiPokok));
                    }
                }
                lblTunjangan.setText("+ Rp 0");
                lblPotongan.setText("- Rp 0");
                lblTotalGaji.setText("Belum diproses");
                lblPeriode.setText("Periode: " + periodeBulanIni);
            }

        } catch (Exception e) {
            e.printStackTrace();
            lblTotalGaji.setText("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnLihatSlipGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatSlipGajiActionPerformed
        // TODO add your handling code here:
        SlipGaji slip = new SlipGaji(
                idPegawai,
                lblNama.getText(),
                lbl_Jabatan.getText(),
                lblInisial.getText()
        );
        slip.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnLihatSlipGajiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TampilanUtamaPegawai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLihatSlipGaji;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblAlpha;
    private javax.swing.JLabel lblBeranda;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGajiBulanIni;
    private javax.swing.JLabel lblGajiPokok;
    private javax.swing.JLabel lblHadir;
    private javax.swing.JLabel lblHeaderInisial;
    private javax.swing.JLabel lblHeaderJabatan;
    private javax.swing.JLabel lblHeaderNama;
    private javax.swing.JLabel lblInisial;
    private javax.swing.JLabel lblIzin;
    private javax.swing.JLabel lblJabatan;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudulHalaman;
    private javax.swing.JLabel lblJudulKehadiran;
    private javax.swing.JLabel lblMenuPegawai;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPeriode;
    private javax.swing.JLabel lblPotongan;
    private javax.swing.JLabel lblPresensi;
    private javax.swing.JLabel lblRingkasanHadir;
    private javax.swing.JLabel lblSakit;
    private javax.swing.JLabel lblSlipGaji;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTelepon;
    private javax.swing.JLabel lblTotalGaji;
    private javax.swing.JLabel lblTunjangan;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lbl_Jabatan;
    private javax.swing.JPanel panelAlpha;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelGaji;
    private javax.swing.JPanel panelHadir;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelIzin;
    private javax.swing.JPanel panelKehadiran;
    private javax.swing.JPanel panelProfil;
    private javax.swing.JPanel panelSakit;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
