package com.mycompany.sistempenggajian;
import java.sql.*;
import javax.swing.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class DialogEditPegawai extends javax.swing.JDialog {
private String idPegawai;
    /**
     * Creates new form DialogEditPegawai
     */
    public DialogEditPegawai(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        this.idPegawai = id;
        initComponents();
        setLocationRelativeTo(parent);
        isiComboBoxJabatan();
        loadData(id);
    }
private void loadData(String id) {
       
        try {
            Connection conn = Koneksi.configDB();
            ResultSet res = conn.createStatement().executeQuery("SELECT * FROM pegawai WHERE id_pegawai = '" + id + "'");
            if (res.next()) {
                txtNik.setText(res.getString("id_pegawai"));
                txtNik.setEditable(false);
                txtNamaLengkap.setText(res.getString("nama_pegawai"));
                txtEmail.setText(res.getString("email"));
                txtNoTelp.setText(res.getString("no_hp"));
                txtAlamat.setText(res.getString("alamat"));
                
                // --- INI CARA BENAR MEMILIH JABATAN DI COMBOBOX ---
                String idJabatanPegawai = res.getString("id_jabatan");
                for (int i = 0; i < cbxJabatan.getItemCount(); i++) {
                    String item = cbxJabatan.getItemAt(i);
                    if (item.startsWith(idJabatanPegawai + " - ")) {
                        cbxJabatan.setSelectedIndex(i);
                        break;
                    }
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaLengkap = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        cbxJabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("EDIT DATA PEGAWAI");

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Nik");

        jLabel4.setText("Email");

        jLabel5.setText("No Telepon");

        jLabel6.setText("Jabatan");

        jLabel7.setText("Alamat");

        txtNik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNikActionPerformed(evt);
            }
        });

        cbxJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJabatanActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbxJabatan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNamaLengkap, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(txtNik)
                                        .addComponent(txtNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(103, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBatal)
                            .addComponent(btnSimpan))
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNikActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
                                   
        try {
            // 1. Ambil nilai dari ComboBox
            String jabatanTerpilih = cbxJabatan.getSelectedItem().toString();
            String idJabatan = "";

            // 2. Cek apakah formatnya sudah benar (mengandung tanda " - ")
            if (jabatanTerpilih.contains(" - ")) {
                idJabatan = jabatanTerpilih.split(" - ")[0].trim();
            } else {
                // Jika format salah (misal isinya cuma "Item 1" atau nama jabatan saja)
                JOptionPane.showMessageDialog(this, "ERROR: Format ComboBox salah!\nNilai yang terbaca: '" + jabatanTerpilih + "'");
                return; // Batalkan proses simpan
            }

            // 3. TAMPILKAN POP-UP UNTUK CEK ID JABATAN
            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Sistem akan menyimpan data ini:\nNIK: " + txtNik.getText() + "\nID Jabatan yang dikirim: '" + idJabatan + "'\n\nApakah ID Jabatan tersebut benar ada di database Anda?", 
                "Cek Data Sebelum Simpan", 
                JOptionPane.YES_NO_OPTION);
                
            if (konfirmasi != JOptionPane.YES_OPTION) {
                return; // Batal simpan jika diklik No
            }

            // 4. Proses Simpan ke Database
            Connection conn = Koneksi.configDB();
            String sql = "UPDATE pegawai SET nama_pegawai=?, email=?, no_hp=?, alamat=?, id_jabatan=? WHERE id_pegawai=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, txtNamaLengkap.getText());
            ps.setString(2, txtEmail.getText());
            ps.setString(3, txtNoTelp.getText());
            ps.setString(4, txtAlamat.getText());
            ps.setString(5, idJabatan); 
            ps.setString(6, txtNik.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbxJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJabatanActionPerformed
        try {
        Connection conn = Koneksi.configDB();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM jabatan");
        cbxJabatan.removeAllItems(); // Bersihkan item lama
        while (rs.next()) {
            // Format: "ID - NamaJabatan"
            cbxJabatan.addItem(rs.getString("id_jabatan") + " - " + rs.getString("nama_jabatan"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load jabatan: " + e.getMessage());
    }
    }//GEN-LAST:event_cbxJabatanActionPerformed
private void isiComboBoxJabatan() {
        try {
            Connection conn = Koneksi.configDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM jabatan");
            
            cbxJabatan.removeAllItems(); // Bersihkan "Item 1, Item 2, dll" bawaan Netbeans
            
            while (rs.next()) {
                // Formatkan menjadi "ID - NamaJabatan"
                cbxJabatan.addItem(rs.getString("id_jabatan") + " - " + rs.getString("nama_jabatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load jabatan: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Baris ini yang akan membuka jendela aplikasi
                new FormDataPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaLengkap;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNoTelp;
    // End of variables declaration//GEN-END:variables
}

