/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.sistempenggajian;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class DialogDetailPresensi extends javax.swing.JDialog {
private DefaultTableModel modelDetail;
    /**
     * Creates new form DialogDetailPresensi
     */
   public DialogDetailPresensi(java.awt.Frame parent, boolean modal, String namaPegawai, String statusBulan) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(parent);
    lblJudulDetail.setText("Detail Presensi — " + namaPegawai + " (" + statusBulan + ")");
    initTable();
    loadDetailPresensi(namaPegawai, statusBulan);
}
    private void initTable() {
        String[] columns = {"TANGGAL", "HARI", "MASUK", "PULANG", "STATUS"};
        modelDetail = new DefaultTableModel(columns, 0);
        tblDetail.setModel(modelDetail);
    }

   private void loadDetailPresensi(String namaPegawai, String statusBulan) {
        modelDetail.setRowCount(0);
        
        // UBAH DI SINI: Ganti jam_keluar menjadi jam_pulang
        String sql = "SELECT pr.tanggal, DAYNAME(pr.tanggal) AS hari, pr.jam_masuk, pr.jam_pulang, pr.status "
                   + "FROM presensi pr "
                   + "JOIN pegawai p ON pr.id_pegawai = p.id_pegawai "
                   + "WHERE p.nama_pegawai = ? AND DATE_FORMAT(pr.tanggal, '%Y-%m') = ? "
                   + "ORDER BY pr.tanggal ASC";

        try (Connection conn = Koneksi.configDB();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, namaPegawai);
            ps.setString(2, statusBulan);
            ResultSet res = ps.executeQuery();
            
            while (res.next()) {
                String hariInggris = res.getString("hari");
                String hariIndo = konversiHari(hariInggris);
                
                modelDetail.addRow(new Object[]{
                    res.getString("tanggal"),
                    hariIndo,
                    res.getString("jam_masuk") != null ? res.getString("jam_masuk") : "-",
                    // UBAH DI SINI: Ganti jam_keluar menjadi jam_pulang
                    res.getString("jam_pulang") != null ? res.getString("jam_pulang") : "-",
                    res.getString("status")
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error Load Data: " + e.getMessage()); 
        }
    }
private String konversiHari(String hari) {
        if (hari == null) return "-";
        switch (hari) {
            case "Monday": return "Senin"; case "Tuesday": return "Selasa";
            case "Wednesday": return "Rabu"; case "Thursday": return "Kamis";
            case "Friday": return "Jumat"; case "Saturday": return "Sabtu";
            case "Sunday": return "Minggu";
            default: return hari;
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblJudulDetail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJudulDetail.setText("Detail Presensi");

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetail);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulDetail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 407, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulDetail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTutup)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogDetailPresensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogDetailPresensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogDetailPresensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogDetailPresensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String contohNama = "Amanda Aulia";
                String contohBulan = "2026-06";
                
                DialogDetailPresensi dialog = new DialogDetailPresensi(new javax.swing.JFrame(), true, contohNama, contohBulan);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTutup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulDetail;
    private javax.swing.JTable tblDetail;
    // End of variables declaration//GEN-END:variables
}
